language: objective-c
xcode_workspace: TravisCI.xcworkspace # path to your xcodeproj folder
xcode_scheme: TravisCI
xcode_sdk: iphonesimulator11.3
osx_image: xcode12.2

script:
  - xcodebuild clean build -sdk iphonesimulator -workspace TravisCI.xcworkspace -scheme TravisCI CODE_SIGNING_REQUIRED=NO